"""change status column type to Enum

Revision ID: aefc31a79080
Revises: e804832e2117
Create Date: 2023-11-15 15:39:47.848278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from apiserver.models import ProjectStatusEnum

# revision identifiers, used by Alembic.
revision: str = 'aefc31a79080'
down_revision: Union[str, None] = 'e804832e2117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    project_status_enum = postgresql.ENUM(
        ProjectStatusEnum,
        name='project_status_enum'
    )
    project_status_enum.create(op.get_bind())

    op.alter_column('project', 'status',
                    existing_type=sa.VARCHAR(length=256),
                    type_=sa.Enum('active', 'delivered', 'vendor_request_sent', 'closed', 'sold', 'lost', 'not_started', name='project_status_enum'),
                    existing_nullable=False,
                    postgresql_using="status::project_status_enum")
    op.add_column('submission', sa.Column('city', sa.String(length=256), nullable=False))
    op.add_column('submission', sa.Column('state', sa.String(length=256), nullable=False))
    op.add_column('submission', sa.Column('location', sa.String(length=256), nullable=False))
    op.add_column('submission', sa.Column('location_description', sa.String(length=256), nullable=True))
    op.add_column('submission', sa.Column('size', sa.String(length=64), nullable=False))
    op.add_column('submission', sa.Column('media_type', sa.String(length=64), nullable=False))
    op.add_column('submission', sa.Column('facing', sa.String(length=16), nullable=False))
    op.add_column('submission', sa.Column('availability', sa.String(length=256), nullable=False))
    op.add_column('submission', sa.Column('is_illuminated', sa.Boolean(), nullable=False))
    op.add_column('submission', sa.Column('four_week_media_cost', sa.Float(), nullable=False))
    op.add_column('submission', sa.Column('a24_49_weekly_expressions', sa.Integer(), nullable=False))
    op.add_column('submission', sa.Column('a18_weekly_expressions', sa.Integer(), nullable=False))
    op.add_column('submission', sa.Column('a18_reach', sa.Float(), nullable=True))
    op.add_column('submission', sa.Column('a18_freq', sa.Float(), nullable=True))
    op.add_column('submission', sa.Column('initial_installation_cost', sa.Float(), nullable=True))
    op.add_column('submission', sa.Column('production_cost', sa.Float(), nullable=True))
    op.add_column('submission', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('submission', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column('submission', sa.Column('no_of_spots', sa.Integer(), nullable=True))
    op.add_column('submission', sa.Column('spot_length', sa.Integer(), nullable=True))
    op.alter_column('submission', 'vendor',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('submission', 'unit',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submission', 'unit',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('submission', 'vendor',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.drop_column('submission', 'spot_length')
    op.drop_column('submission', 'no_of_spots')
    op.drop_column('submission', 'longitude')
    op.drop_column('submission', 'latitude')
    op.drop_column('submission', 'production_cost')
    op.drop_column('submission', 'initial_installation_cost')
    op.drop_column('submission', 'a18_freq')
    op.drop_column('submission', 'a18_reach')
    op.drop_column('submission', 'a18_weekly_expressions')
    op.drop_column('submission', 'a24_49_weekly_expressions')
    op.drop_column('submission', 'four_week_media_cost')
    op.drop_column('submission', 'is_illuminated')
    op.drop_column('submission', 'availability')
    op.drop_column('submission', 'facing')
    op.drop_column('submission', 'media_type')
    op.drop_column('submission', 'size')
    op.drop_column('submission', 'location_description')
    op.drop_column('submission', 'location')
    op.drop_column('submission', 'state')
    op.drop_column('submission', 'city')
    op.alter_column('project', 'status',
                    existing_type=sa.Enum('active', 'delivered', 'vendor_request_sent', 'closed', 'sold', 'lost', 'not_started', name='project_status_enum'),
                    type_=sa.VARCHAR(length=256),
                    existing_nullable=False)

    project_status_enum = postgresql.ENUM(
        ProjectStatusEnum,
        name='project_status_enum'
    )
    project_status_enum.drop(op.get_bind())
    # ### end Alembic commands ###
