"""added size, raw_date column

Revision ID: 1bfa3dda6091
Revises: b5fea131894e
Create Date: 2023-12-18 15:18:37.601064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bfa3dda6091'
down_revision: Union[str, None] = 'b5fea131894e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('size', sa.String(length=32), nullable=True))
    op.add_column('submissions', sa.Column('raw_installation_cost', sa.String(length=32), nullable=True))
    op.add_column('submissions', sa.Column('raw_date', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'raw_date')
    op.drop_column('submissions', 'raw_installation_cost')
    op.drop_column('submissions', 'size')
    # ### end Alembic commands ###
