"""added image_id, unit_id, on_of_periods in submission

Revision ID: 279d7d8d416a
Revises: 1bfa3dda6091
Create Date: 2023-12-21 15:18:48.967923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '279d7d8d416a'
down_revision: Union[str, None] = '1bfa3dda6091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('one_week_media_cost', sa.Float(), nullable=True))
    op.add_column('submissions', sa.Column('two_week_media_cost', sa.Float(), nullable=True))
    op.add_column('submissions', sa.Column('three_week_media_cost', sa.Float(), nullable=True))
    op.add_column('submissions', sa.Column('no_of_periods', sa.Integer(), nullable=True))
    op.add_column('submissions', sa.Column('weeks_in_a_period', sa.Integer(), nullable=True))
    op.add_column('submissions', sa.Column('image_id', sa.String(length=1024), nullable=True))
    op.alter_column('submissions', 'distance_to_location',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('submissions', 'unit', new_column_name='unit_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'unit_id', new_column_name='unit')
    op.alter_column('submissions', 'distance_to_location',
               existing_type=sa.String(length=256),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('submissions', 'image_id')
    op.drop_column('submissions', 'weeks_in_a_period')
    op.drop_column('submissions', 'no_of_periods')
    op.drop_column('submissions', 'three_week_media_cost')
    op.drop_column('submissions', 'two_week_media_cost')
    op.drop_column('submissions', 'one_week_media_cost')
    # ### end Alembic commands ###
