"""added cost_basis col in submission

Revision ID: 3ea8b71ab8b9
Revises: a55c10b1d7af
Create Date: 2023-12-26 16:35:12.722715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from apiserver.models import CostBasisEnum

# revision identifiers, used by Alembic.
revision: str = '3ea8b71ab8b9'
down_revision: Union[str, None] = 'a55c10b1d7af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    cost_basis_enum = postgresql.ENUM(
        CostBasisEnum,
        name='cost_basis_enum'
    )
    cost_basis_enum.create(op.get_bind())

    op.add_column('submissions', sa.Column('cost_basis', sa.Enum('one_week_media_cost', 'two_week_media_cost', 'three_week_media_cost', 'four_week_media_cost', name='cost_basis_enum'), server_default='four_week_media_cost', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'cost_basis')

    cost_basis_enum = postgresql.ENUM(
        CostBasisEnum,
        name='cost_basis_enum'
    )
    cost_basis_enum.drop(op.get_bind())
    # ### end Alembic commands ###
