"""deleted weeks_in_period column

Revision ID: 74d34ba5160f
Revises: 3ea8b71ab8b9
Create Date: 2024-01-01 18:41:10.777884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d34ba5160f'
down_revision: Union[str, None] = '3ea8b71ab8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'weeks_in_a_period')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('weeks_in_a_period', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
