"""is_prod_force_nullable__and_size_255

Revision ID: ed7aa71905f8
Revises: 74d34ba5160f
Create Date: 2024-01-03 11:35:40.018087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed7aa71905f8'
down_revision: Union[str, None] = '74d34ba5160f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'size',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('submissions', 'is_prod_forced',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'is_prod_forced',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('submissions', 'size',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###
