name: Update Docker Containers on Azure VM

on:
  push:
    branches:
      - main

jobs:
  update_containers:
    runs-on: ubuntu-latest

    steps:

    - name: display files
      run: git clone https://github.com/waqas-ahmed124/wilkins-api-test.git ; cd wilkins-api-test ; git checkout main ; ls ; cat docker-compose.yaml

    - name: Display Public Key
      run: cat ~/.ssh/id_rsa.pub

    - name: Configure SSH Key
      run: |
        echo -e "Host 172.203.185.112\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

    - name: Update Docker Containers on Azure VM
      run: |
        ssh -v -i ~/.ssh/id_rsa azureuser@172.203.185.112 'cd /home/azureuser/wilkins-api && docker-compose pull && docker-compose up -d'
      env:
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
