name: SSH into VM

on:
  push:
    branches:
      - main

jobs:
  sshJob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" > ~/.ssh/config

      - name: SSH into VM
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@172.203.185.112 "pwd; cd test; git clone https://github.com/waqas-ahmed124/wilkins-api-test.git; ls -larth; cd wilkins-api-test; git checkout main; cd /home/azureuser/test/wilkins-api-test && docker-compose pull && docker-compose up --build ";  
