name: Update Docker Containers on Azure VM

on:
  push:
    branches:
      - main

jobs:
  update_containers:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Generate SSH Key Pair
      run: |
        ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ''

    - name: Display Public Key
      run: cat ~/.ssh/id_rsa.pub

    - name: Configure SSH Key
      run: |
        echo -e "Host 172.203.185.112\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

    - name: Update Docker Containers on Azure VM
      run: |
        ssh -v -i ~/.ssh/id_rsa azureuser@172.203.185.112 'cd /home/azureuser/wilkins-api && docker-compose pull && docker-compose up -d'
      env:
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
