name: Run SSH Script

on: [push]

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run SSH Script
      run: |
        chmod +x sd.sh
        ./sd.sh
