name: Update Docker Containers on Azure VM

on:
  push:
    branches:
      - main

jobs:
  update_containers:
    runs-on: ubuntu-latest

    steps:

    - name: display files
      run: git clone https://github.com/waqas-ahmed124/wilkins-api-test.git ; cd wilkins-api-test ; git checkout main ; ls ; cat docker-compose.yaml

    - name: Display Public Key
       
      run: |
        ls; cd wilkins-api-test; 
        ls; 
        chmod 600 BeyondGen.pem ; ssh -o StrictHostKeyChecking=no -i "BeyondGen.pem" azureuser@172.203.185.112 "pwd; cd /home/azureuser/test ; git clone https://github.com/waqas-ahmed124/wilkins-api-test.git ; ls -larth; cd /home/azureuser/test/wilkins-api-test ; git checkout main ; cd /home/azureuser/test/wilkins-api-test && docker-compose pull && docker-compose up --build ";

